Add Offline OPD Visit Count Report
Bahmni-HWC/clinic-config pull request #57
Opened 2023-07-24 07:25 UTC by poojadeshpande01

Add Offline OPD Visit Count Report

2023-07-24 07:31 UTC, poojadeshpande01 commented
<img width="1316" alt="image" src="https://github.com/Bahmni-HWC/clinic-config/assets/92026860/34ee444b-7026-433e-968e-068248d4a270">

2023-07-24 10:47 UTC, mohan-13 commented
Integration user should not be shown. Those are patients synced from online to offline

2023-07-24 11:03 UTC, riyaTw approved these changes

2023-07-24 11:06 UTC, riyaTw requested changes
Can we change Column name as "Location"

2023-07-24 11:06 UTC, riyaTw approved these changes

2023-07-25 01:49 UTC, mohan-13 requested changes

2023-07-25 01:49 UTC, mohan-13 commented on openmrs/apps/reports/sql/offlineOPDVisitCount.sql
> +SELECT u.name AS User, c.name AS Location, COUNT(DISTINCT e.individual_id) AS "Offline OPD Visit Count"
Count of distinct individual id will give only the number of patients that had an encounter in the date range. This should be grouped by date also and then sum should be taken

2023-07-25 10:22 UTC, closed without merging